name: timer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    

  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital7/digital-7.ttf
        - asset: 'assets/fonts/digital7/digital-7 (italic).ttf'
          style: italic

    
    - family: Digital7Mono
      fonts:
        - asset: 'assets/fonts/digital7/digital-7 (mono).ttf'
        - asset: 'assets/fonts/digital7/digital-7 (mono italic).ttf'
          style: italic